/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface_Graphique;

import java.awt.GridBagLayout;
import java.awt.event.ActionListener;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import sudoku.Coup;
import sudoku.Grille;
import sudoku.Sudoku;

/**
 *
 * @author yannE
 */

/**
 * Fenêtre représentant le "pad numérique"
 * @author yannE
 */
public class FrameChoice extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form FrameChoice
     */
    public FrameChoice() {
        initComponents();
    }
    
    public FrameChoice(PanelGrille pg){
        initComponents();
        this.pg = pg;
        for (int i = 1; i <= pg.getTailleAuCarree(); i++){
            JButton button = new JButton(""+(i));
            jPanel1.add(button);
            button.addActionListener(this);
        }
        
        this.currentIndex = -1;
        jPanel1.setLayout(new BoxLayout(jPanel1,BoxLayout.X_AXIS));
        
        
    }
    
    @Override
    public void actionPerformed(java.awt.event.ActionEvent evt){
        int valeur = Integer.parseInt(evt.getActionCommand()); 
                                                                  
        Grille g = pg.getSudoku().getGrille();
        int valeurDeLaCaseAvant = g.getValeurCase(currentIndex);
        // Case sans valeur, ni candidats
        
        if (g.getValeurCase(currentIndex) == 0 && g.getCandidatCase(currentIndex).isEmpty()){
            g.setValeurCase(currentIndex, valeur);
        }
        // Case sans valeur, avec des candidats
        else if (g.getValeurCase(currentIndex) == 0 && !g.getCandidatCase(currentIndex).isEmpty()){
            if(!g.getCandidatCase(currentIndex).contains(valeur)){
                g.addCandidatCase(currentIndex,valeur);
            }
            else{
                g.removeCandidatCase(currentIndex,valeur);
                if (g.getCandidatCase(currentIndex).size() == 1){
                    int valeurCase = g.getCandidatCase(currentIndex).get(0);
                    g.setValeurCase(currentIndex,valeurCase);
                    g.removeCandidatCase(currentIndex,valeurCase);
            }
            }
            
        }
        else { // Case avec valeur
            
            g.setValeurCase(currentIndex, 0);
            if (valeurDeLaCaseAvant != valeur && valeurDeLaCaseAvant != 0) {
                g.addCandidatCase(currentIndex, valeurDeLaCaseAvant);
                pg.drawGrille(PanelGrille.Draw.GRILLE);
                g.addCandidatCase(currentIndex,valeur);
            }
        }
        
        
        pg.drawGrille(PanelGrille.Draw.GRILLE);
        // ON RAJOUTE L'EVOLUTION DES COUPS ICI
        pg.getSudoku().addCoup(new Coup(currentIndex,valeurDeLaCaseAvant,g.getValeurCase(currentIndex)));
        
        
        
        
    }
    
    public void setCurrentIndex(int index){
        currentIndex = index;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameChoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    // More variables
    
    private PanelGrille pg;
    private int currentIndex;

}
